import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Lexora",
};

export default function PrivacyPage() {
  return (
    <main id="main-content" className="mx-auto max-w-2xl px-4 py-12">
      <div className="mb-8 rounded-lg border border-warning/40 bg-warning/10 p-4 text-sm text-foreground">
        <strong className="font-semibold">Draft, not legal advice.</strong>{" "}
        This page describes what the app actually does in plain language.
        Have it reviewed by an actual lawyer before relying on it for a real
        public launch — it hasn&apos;t been.
      </div>

      <h1 className="font-heading text-3xl leading-tight font-semibold tracking-tight text-foreground">
        Privacy Policy
      </h1>
      <p className="mt-1 text-sm text-muted-foreground">Last updated 2026-07-18.</p>

      <div className="mt-8 flex flex-col gap-6 text-foreground [&_h2]:font-heading [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:mb-2 [&_p]:text-sm [&_p]:text-muted-foreground [&_p]:leading-relaxed [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:text-sm [&_ul]:text-muted-foreground [&_ul]:leading-relaxed [&_ul]:flex [&_ul]:flex-col [&_ul]:gap-1">
        <section>
          <h2>No account, no personal sign-up</h2>
          <p>
            Lexora doesn&apos;t have accounts, emails, or passwords. On your
            first visit, we set one cookie — a random id with no personal
            information in it — so your saved words, streak, and badges stay
            with your browser between visits.
          </p>
        </section>

        <section>
          <h2>What we store</h2>
          <ul>
            <li>The anonymous cookie id, and whatever words/notes/tags you save under it.</li>
            <li>The text you search and, separately, your IP address — kept briefly to stop abuse of the search feature, not to identify you personally.</li>
            <li>If you generate a recovery code, that code and which anonymous id it points to.</li>
          </ul>
        </section>

        <section>
          <h2>Who else sees your data</h2>
          <p>
            Word lookups and definitions are generated by Groq, a third-party
            AI provider — the text you search is sent to them to produce a
            result. The app itself runs on Netlify, with data stored in a
            Postgres database. No advertising networks or analytics trackers
            are used.
          </p>
        </section>

        <section>
          <h2>Your control over it</h2>
          <p>
            Delete any saved word individually from the Favorites page, or
            use &quot;Delete all my data&quot; there to permanently erase
            everything tied to your device in one step. Because there&apos;s
            no account, we have no way to verify a deletion request that
            doesn&apos;t come from your own browser or recovery code.
          </p>
        </section>

        <section>
          <h2>Losing access</h2>
          <p>
            Since your identity is just a cookie, clearing cookies, switching
            browsers, or reinstalling means losing access to your saved
            words unless you&apos;ve backed up a recovery code first.
          </p>
        </section>
      </div>
    </main>
  );
}
