import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use — Lexora",
};

export default function TermsPage() {
  return (
    <main id="main-content" className="mx-auto max-w-2xl px-4 py-12">
      <div className="mb-8 rounded-lg border border-warning/40 bg-warning/10 p-4 text-sm text-foreground">
        <strong className="font-semibold">Draft, not legal advice.</strong>{" "}
        Have an actual lawyer review and finalize these terms before relying
        on them for a real public launch.
      </div>

      <h1 className="font-heading text-3xl leading-tight font-semibold tracking-tight text-foreground">
        Terms of Use
      </h1>
      <p className="mt-1 text-sm text-muted-foreground">Last updated 2026-07-18.</p>

      <div className="mt-8 flex flex-col gap-6 text-foreground [&_h2]:font-heading [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:mb-2 [&_p]:text-sm [&_p]:text-muted-foreground [&_p]:leading-relaxed">
        <section>
          <h2>AI-generated content</h2>
          <p>
            Definitions, etymology, CEFR level, difficulty, and related-word
            suggestions are generated by an AI model, not sourced from a
            certified linguistic corpus. They&apos;re usually accurate but
            can occasionally be wrong or oversimplified — treat them as a
            helpful starting point, not an authoritative dictionary.
          </p>
        </section>

        <section>
          <h2>No account means no data guarantees</h2>
          <p>
            Your saved words are tied to a browser cookie, not a verified
            identity. If you lose that cookie without backing up a recovery
            code first, we have no way to recover your data — there&apos;s
            no account to reset a password on.
          </p>
        </section>
      </div>
    </main>
  );
}
